language: php

php:
    - 5.4
    - 5.5

services:
    - mongodb

before_script:
    - phpenv config-add .travis.php.ini
    - cp config/parameters.yml.dist config/parameters.yml
    - wget http://getcomposer.org/composer.phar -nc
    - php composer.phar dump-autoload
    - php composer.phar install

script: phpunit
